// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaceDay.Data;

#nullable disable

namespace RaceDay.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260926105740_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RaceDay.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrolmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ParticipantID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ParticipantID", "CategoryID")
                        .IsUnique();

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("RaceDay.Models.Event", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrganiserID")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("EventID");

                    b.HasIndex("OrganiserID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("RaceDay.Models.EventCategory", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("DistanceKm")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("EntryFee")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.HasKey("CategoryID");

                    b.HasIndex("EventID");

                    b.ToTable("EventCategories");
                });

            modelBuilder.Entity("RaceDay.Models.Result", b =>
                {
                    b.Property<int>("ResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultID"));

                    b.Property<int>("CapturedByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CapturedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnrollmentID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("FinishTime")
                        .HasColumnType("time");

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.HasKey("ResultID");

                    b.HasIndex("CapturedByUserID");

                    b.HasIndex("EnrollmentID")
                        .IsUnique();

                    b.ToTable("Results");
                });

            modelBuilder.Entity("RaceDay.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleID");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleID = 2,
                            RoleName = "Organiser"
                        },
                        new
                        {
                            RoleID = 3,
                            RoleName = "Participant"
                        });
                });

            modelBuilder.Entity("RaceDay.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RaceDay.Models.Enrollment", b =>
                {
                    b.HasOne("RaceDay.Models.EventCategory", "Category")
                        .WithMany("Enrollments")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaceDay.Models.User", "Participant")
                        .WithMany("Enrollments")
                        .HasForeignKey("ParticipantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("RaceDay.Models.Event", b =>
                {
                    b.HasOne("RaceDay.Models.User", "Organiser")
                        .WithMany("OrganisedEvents")
                        .HasForeignKey("OrganiserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organiser");
                });

            modelBuilder.Entity("RaceDay.Models.EventCategory", b =>
                {
                    b.HasOne("RaceDay.Models.Event", "Event")
                        .WithMany("Categories")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("RaceDay.Models.Result", b =>
                {
                    b.HasOne("RaceDay.Models.User", "CapturedByUser")
                        .WithMany("CapturedResults")
                        .HasForeignKey("CapturedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaceDay.Models.Enrollment", "Enrollment")
                        .WithOne("Result")
                        .HasForeignKey("RaceDay.Models.Result", "EnrollmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CapturedByUser");

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("RaceDay.Models.User", b =>
                {
                    b.HasOne("RaceDay.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RaceDay.Models.Enrollment", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("RaceDay.Models.Event", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("RaceDay.Models.EventCategory", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("RaceDay.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("RaceDay.Models.User", b =>
                {
                    b.Navigation("CapturedResults");

                    b.Navigation("Enrollments");

                    b.Navigation("OrganisedEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
